# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# print(AWS_ACCESS_KEY_ID + " " + AWS_SECRET_ACCESS_KEY)

# DATABASE_PASS = ""
# print(DATABASE_PASS)

SSH_SECRET_KEY="
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAhdPL4VGk1vvBO/7doLXPuJ9RRClfFAYGvhe6TGiu60AAAAJhaEhrJWhIa
yQAAAAtzc2gtZWQyNTUxOQAAACAhdPL4VGk1vvBO/7doLXPuJ9RRClfFAYGvhe6TGiu60A
AAAEBW5oxYhH0uUhiO1AugsZfZ9SRxoUfCda7UnyvPriDBNiF08vhUaTW+8E7/t2gtc+4n
1FEKV8UBga+F7pMaK7rQAAAAEm1zaGVzdGFseXVrQE1ha3NQQwECAw==
-----END OPENSSH PRIVATE KEY-----
"