# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# print(AWS_ACCESS_KEY_ID + " " + AWS_SECRET_ACCESS_KEY)

# DATABASE_PASS = ""
# print(DATABASE_PASS)

# SSH_SECRET_KEY = ""
SSH_PUB_KEY = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICF08vhUaTW+8E7/t2gtc+4n1FEKV8UBga+F7pMaK7rQ mshestalyuk@MaksPC"