# AWS_ACCESS_KEY_ID = ""
# AWS_SECRET_ACCESS_KEY = ""
# print(AWS_ACCESS_KEY_ID + " " + AWS_SECRET_ACCESS_KEY)

# DATABASE_PASS = ""
# print(DATABASE_PASS)

# SSH_SECRET_KEY = ""
SSH_PUB_KEY = ""

DOCKER_ACCESS = ""
TEST_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"