name: "GitLeaks CI"
on:
 push:

jobs:
    git-leaks:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
              with:
                fetch-depth: 0
            - name: GitLeaks Secret Scanning
              uses: gitleaks/gitleaks-action@v3
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
